steps:
  - name: >-
      asia-south1-docker.pkg.dev/ibank-docai-devops/ibci-docai-docker-ar/cloudbuild/pycov/mlops:latest
    args:
      - '-c'
      - >
        pip install -r requirements.txt --extra-index-url
        https://asia-south1-python.pkg.dev/ibank-docai-devops/ibci-docai-python-ar/simple
        && source /app/variables.env &&  pytest tests/unit/src/mlops_pipeline
        --cov=src/mlops_pipeline
    id: Code Coverage
    entrypoint: bash
  - name: >-
      asia-south1-docker.pkg.dev/ibank-docai-devops/ibci-docai-docker-ar/cloudbuild/docker:latest
    args:
      - '-c'
      - >
        docker build --network=cloudbuild -t
        ${_REPOSITORY_URL}/${_IMAGE}:${TAG_NAME} -f
        ./src/mlops_pipeline/cdc_pipeline/components/training/Dockerfile .
    id: Build container image
    entrypoint: /bin/bash
  - name: >-
      asia-south1-docker.pkg.dev/ibank-docai-devops/ibci-docai-docker-ar/cloudbuild/docker:latest
    args:
      - '-c'
      - >
        docker tag ${_REPOSITORY_URL}/${_IMAGE}:${TAG_NAME} ${_REPOSITORY_URL}/${_IMAGE}:latest &&
        docker push ${_REPOSITORY_URL}/${_IMAGE}:latest && docker push ${_REPOSITORY_URL}/${_IMAGE}:${TAG_NAME}
    id: Tag Container image
    entrypoint: /bin/bash
  - name: >-
      asia-south1-docker.pkg.dev/ibank-docai-devops/ibci-docai-docker-ar/cloudbuild/pycov/mlops:latest
    args:
      - '-c'
      - |
        ./cdc_ee_pp_spec.sh
    id: spec file genaration
    entrypoint: /bin/bash
timeout: 800s
options:
  workerPool: >-
    projects/ibank-docai-devops/locations/asia-south1/workerPools/ibsi-docai-devops-cb-wp01
  logging: CLOUD_LOGGING_ONLY
