# Deleting Datalake support infra.
# Once succeded, Terraform destroys the infrastructure (IaC).
# Should be run once, after Datalake is deleted.
# Triggered manually:
#   workflow_dispatch -> select branch
# Workflow:
#   - Set up environment and get short SHA 
#   - Cleanup GCP with Terraform

name: Manual - Delete infrastructure with Terraform

on:
  workflow_dispatch:

env:
  TF_PLAN_FILE: terraform.tfplan

defaults:
  run:
    working-directory: terraform/infra

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    name: Prerequisites
    runs-on: ubuntu-latest

    steps:
      # Checkout the head commit in a detached head state.
      - name: Checkout the latest commit
        uses: actions/checkout@v2

      - name: Check branch and set environment
        id: check_branch
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo '::set-output name=env_name::production'
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo '::set-output name=env_name::develop'
          fi

    outputs:
      env_name: ${{ steps.check_branch.outputs.env_name }}

  deploy:
    name: Deploy GCP with Terraform
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: ${{ needs.prepare.outputs.env_name }}
    env:
      TF_VAR_project: ${{ secrets.GOOGLE_PROJECT_ID }}

    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init -backend-config=bucket=${{ secrets.GOOGLE_PROJECT_ID }}-state

      - name: Terraform validate
        run: terraform validate

      - name: Terraform destroy
        run: terraform destroy -auto-approve
