# Uploading Dataflow artifacts and deploying Google Cloud with Terraform.
# Triggered on push to either `main` or `develop`.
# Workflow:
#   - Set up environment, create list of clients and get short SHA
#   - If detaflow/** changed:
#       \_Build Docker image
#         Create Dataflow template
#         Notify in Slack
#   - Deploy GCP with Terraform

name: Deploy Google Cloud staging

on:
  push:
    branches:
      - develop
    paths:
      - .github/**
      - conf/**
      - dataflow/**
      - terragenesis/**
      - monitoring/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    name: Prerequisites
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scripts

    steps:
      # Checkout the head commit in a detached head state.
      - name: Checkout the latest commit
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate a list of clients
        id: looper
        run: |
          python iterate_config.py ../conf

      # Get commit short SHA.
      - name: Get commit SHA
        id: hash
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

    outputs:
      folders: ${{ steps.looper.outputs.folders }}
      short_sha: ${{ steps.hash.outputs.short_sha }}

  deploy-infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: staging
    env:
      TF_PLAN_FILE: terraform.tfplan
      TF_VAR_project: ${{ secrets.GOOGLE_PROJECT_ID }}
      TF_VAR_env: staging
      TF_VAR_github_private_access_token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      TF_VAR_publisher_project_id: ${{ secrets.PUBLISHER_PROJECT_ID }}
      TF_VAR_slack: "{\"notification_channel\":\"${{ secrets.SLACK_CHANNEL }}\",\"auth_token\":\"${{ secrets.SLACK_AUTH_TOKEN }}\"}"
      TF_VAR_opsgenie_token: ${{ secrets.OPSGENIE_TOKEN }}

    defaults:
      run:
        working-directory: terragenesis/stacks/infra

    # Create infrastructure resources.
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Infra - Format
        run: terraform fmt -check

      - name: Infra - Init
        run: terraform init -backend-config=bucket=${{ secrets.GOOGLE_PROJECT_ID }}-state

      - name: Infra - Validate
        run: terraform validate

      - name: Infra - Plan
        run: terraform plan -out ${{ env.TF_PLAN_FILE }}

      - name: Infra - Apply
        run: terraform apply ${{ env.TF_PLAN_FILE }}

  bake:
    name: Build the Dataflow flex template
    runs-on: ubuntu-latest
    needs: [prepare, deploy-infra]
    environment:
      name: staging
    env:
      TEMPLATE_IMAGE: gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/takeoff-dl-ingest:${{ needs.prepare.outputs.short_sha }}
      TEMPLATE_PATH: gs://${{ secrets.GOOGLE_PROJECT_ID }}-dataflow/templates/takeoff-dl-ingest-${{ needs.prepare.outputs.short_sha }}.json

    defaults:
      run:
        working-directory: dataflow/template

    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v3

      - name: Get specific changed files
        id: dataflow_files
        uses: tj-actions/changed-files@v31.0.2
        with:
          files: |
            dataflow/**

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        if: (github.event_name == 'push' && steps.dataflow_files.outputs.any_changed == 'true') || github.event_name == 'workflow_dispatch'
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        if: (github.event_name == 'push' && steps.dataflow_files.outputs.any_changed == 'true') || github.event_name == 'workflow_dispatch'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Build image
        if: (github.event_name == 'push' && steps.dataflow_files.outputs.any_changed == 'true') || github.event_name == 'workflow_dispatch'
        run: gcloud builds submit --tag ${{ env.TEMPLATE_IMAGE }} .

      - name: Create a template
        if: (github.event_name == 'push' && steps.dataflow_files.outputs.any_changed == 'true') || github.event_name == 'workflow_dispatch'
        run: |
          gcloud dataflow flex-template build ${{ env.TEMPLATE_PATH }} \
            --image ${{ env.TEMPLATE_IMAGE }} \
            --sdk-language PYTHON

  deploy-datalake:
    name: Deploy GCP with Terraform
    runs-on: ubuntu-latest
    needs: [prepare, bake]
    environment:
      name: staging
    env:
      TF_VAR_project: ${{ secrets.GOOGLE_PROJECT_ID }}
      TF_VAR_env: staging
      TF_VARS_FILE: terraform.auto.tfvars.json
      TF_PLAN_FILE: terraform.tfplan

    defaults:
      run:
        working-directory: terragenesis/stacks/datalake

    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.prepare.outputs.folders) }}

    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v3

      # Check, if Dataflow specific files changed.
      # These files can cause the compatibility check to fail.
      # See https://cloud.google.com/dataflow/docs/guides/updating-a-pipeline#CCheck for details. 
      - name: Get specific changed files
        id: compat_check
        uses: tj-actions/changed-files@v31.0.2
        with:
          files: |
            conf/${{ matrix.folder }}/**
            dataflow/**

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Get the Dataflow image tag
        id: get_image
        run: |
          echo "::set-output name=image_tag::$(gcloud container images list-tags gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/takeoff-dl-ingest \
            --limit 1 --format 'value(tags)')"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip

      - name: Install Python dependencies
        run: pip install -r ../../../scripts/requirements.txt

      - name: Generate .tfvars from the client config
        run: |
          python ../../../scripts/prefly.py ${{ matrix.folder }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Datalake - Format
        run: terraform fmt -check

      - name: Datalake - Init
        run: terraform init -backend-config=bucket=${{ secrets.GOOGLE_PROJECT_ID }}-state

      - name: Datalake - Workspace
        run: terraform workspace new ${{ matrix.folder }} || terraform workspace select ${{ matrix.folder }}

      - name: Datalake - Validate
        run: terraform validate

      # Replace Dataflow resource if related files changed.
      # The job will be drained gracefully in prod and simply cancelled in non-prod environments.
      - name: Datalake - Plan (Dataflow replace)
        if: (github.event_name == 'push' && steps.compat_check.outputs.any_changed == 'true') || github.event_name == 'workflow_dispatch'
        env:
          TF_VAR_template_path: gs://${{ secrets.GOOGLE_PROJECT_ID }}-dataflow/templates/takeoff-dl-ingest-${{ steps.get_image.outputs.image_tag }}.json
        run: terraform plan -var-file=${{ env.TF_VARS_FILE }} -out ${{ env.TF_PLAN_FILE }} -replace "google_dataflow_flex_template_job.df_job"

      - name: Datalake - Plan
        if: github.event_name == 'push' && steps.compat_check.outputs.any_changed == 'false'
        env:
          TF_VAR_template_path: gs://${{ secrets.GOOGLE_PROJECT_ID }}-dataflow/templates/takeoff-dl-ingest-${{ steps.get_image.outputs.image_tag }}.json
        run: terraform plan -var-file=${{ env.TF_VARS_FILE }} -out ${{ env.TF_PLAN_FILE }}

      - name: Datalake - Apply
        run: terraform apply ${{ env.TF_PLAN_FILE }}

  deploy-monitoring:
    name: Deploy monitoring
    runs-on: ubuntu-latest
    needs: deploy-datalake
    environment:
      name: staging
    env:
      TF_PLAN_FILE: terraform.tfplan
      TF_VAR_project: ${{ secrets.GOOGLE_PROJECT_ID }}
      TF_VAR_env: staging

    defaults:
      run:
        working-directory: terragenesis/stacks/monitoring

    # Create infrastructure resources.
    steps:
      - name: Checkout the latest commit
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Monitoring - Format
        run: terraform fmt -check

      - name: Monitoring - Init
        run: terraform init -backend-config=bucket=${{ secrets.GOOGLE_PROJECT_ID }}-state

      - name: Monitoring - Validate
        run: terraform validate

      - name: Monitoring - Plan
        run: terraform plan -out ${{ env.TF_PLAN_FILE }}

      - name: Monitoring - Apply
        run: terraform apply ${{ env.TF_PLAN_FILE }}
